language: nix
jobs:
  include:
  - env:
    # GHC 8.2.2
    - NIX_CHANNEL=https://nixos.org/channels/nixos-19.09
    - STACK_RESOLVER=lts-11.22
  - env:
    # GHC 8.4.4
    - NIX_CHANNEL=https://nixos.org/channels/nixos-19.09
    - STACK_RESOLVER=lts-12.26
  - env:
    # GHC 8.6.5
    - NIX_CHANNEL=https://nixos.org/channels/nixos-19.09
    - STACK_RESOLVER=lts-14.12
  - env:
    # GHC 8.8.1
    - NIX_CHANNEL=https://nixos.org/channels/nixos-19.09
    - STACK_RESOLVER=nightly-2019-10-27

before_install:
  # configure Nix https://nixos.wiki/wiki/Nix_on_Travis
  - sudo mkdir -p /etc/nix
  - echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo 'sandbox = true' | sudo tee -a /etc/nix/nix.conf > /dev/null
  # Download and unpack the stack executable https://docs.haskellstack.org/en/stable/travis_ci/#installing-stack
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - nix-channel --remove nixpkgs
  - nix-channel --add $NIX_CHANNEL nixpkgs
  - nix-channel --update

script:
  - stack build --test --copy-bins --prefetch --coverage --resolver $STACK_RESOLVER

after_script:
  - export PACKAGE_NAME=codecov-haskell
  - export MIX_DIR="$(stack path --dist-dir)/hpc/"
  - export TIX_DIR="$(stack path --local-hpc-root)/$PACKAGE_NAME/"
  - codecov-haskell test-all --exclude-dir=test --display-report --print-response --combined=false --exclude-dir test --mix-dir $MIX_DIR --tix-dir $TIX_DIR --token=$CODECOV_TOKEN

cache:
  directories:
  - $HOME/nix.store
  - $HOME/.stack

before_cache:
# cache Nix store https://nixos.wiki/wiki/Nix_on_Travis
- mkdir -p $HOME/nix.store
- nix copy --to file://$HOME/nix.store -f default.nix buildInputs
